{% set data = load_setup_py_data() %}

package:
  name: plio
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/USGS-Astrogeology/plio

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: dev

extra:
  channels:
    - usgs-astrogeology
    - conda-forge

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pvl
    - protobuf
    - gdal
    - icu
    - h5py
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - scipy
    - certifi
  run:
    - python
    - setuptools
    - numpy
    - pvl
    - protobuf
    - gdal
    - icu
    - h5py
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - scipy
    - certifi
    - pyproj
    - jinja2


test:
  imports:
    - plio

about:
  home: http://github.com/USGS-Astrogeology/plio
  license: Public Domain
