package:
  name: plio
  version: 0.1.0

source:
  git_url: https://github.com/USGS-Astrogeology/plio

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pvl
    - protobuf
    - gdal
    - icu
    - h5py
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - scipy
    - certifi
  run:
    - python
    - setuptools
    - numpy
    - pvl
    - protobuf
    - gdal
    - icu
    - h5py
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - scipy
    - certifi

test:
  imports:
    - plio

about:
  home: http://github.com/USGS-Astrogeology/plio
  license: Public Domain
