package:
  name: plio
  version: 0.1.4

source:
  git_url: https://github.com/USGS-Astrogeology/plio

build:
  number: 1

extra:
  channels:
    - usgs-astrogeology
    - conda-forge

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pvl
    - protobuf
    - gdal
    - icu
    - h5py
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - scipy
    - certifi
  run:
    - python
    - setuptools
    - numpy
    - pvl
    - protobuf
    - gdal
    - icu
    - h5py
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
    - scipy
    - certifi
    - pyproj
    - cycsm
    - usgscam
    - jinja2

test:
  imports:
    - plio

about:
  home: http://github.com/USGS-Astrogeology/plio
  license: Public Domain
