name: plio
channels:
  - conda-forge
dependencies:
  - affine
  - coveralls
  - gdal
  - h5py
  - libprotobuf >=4,<5
  - nbsphinx
  - networkx
  - numpy
  - pandas
  - protobuf >=4,<5
  - pvl >= 1.3.0
  - pyproj
  - pytest
  - pytest-cov
  - pyyaml
  - scipy
  - setuptools
  - sphinx
  - sqlalchemy
