name: plio
channels:
  - conda-forge
dependencies:
  - gdal 
  - numpy 
  - pyproj 
  - h5py 
  - pvl >= 1.3.0
  - scipy 
  - protobuf 
  - affine 
  - networkx 
  - pandas 
  - sqlalchemy 
  - pyyaml 
  - pytest 
  - pytest-cov 
  - coveralls 
  - nbsphinx
  - sphinx
