# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ControlNetFileHeaderV0002.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43ontrolNetFileHeaderV0002.proto\x12\x04Isis\"\xaf\x01\n\x19\x43ontrolNetFileHeaderV0002\x12\x11\n\tnetworkId\x18\x01 \x02(\t\x12\x12\n\ntargetName\x18\x02 \x02(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\t\x12\x14\n\x0clastModified\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x10\n\x08userName\x18\x06 \x01(\t\x12\x1d\n\x11pointMessageSizes\x18\x07 \x03(\x05\x42\x02\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ControlNetFileHeaderV0002_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTROLNETFILEHEADERV0002'].fields_by_name['pointMessageSizes']._options = None
  _globals['_CONTROLNETFILEHEADERV0002'].fields_by_name['pointMessageSizes']._serialized_options = b'\020\001'
  _globals['_CONTROLNETFILEHEADERV0002']._serialized_start=42
  _globals['_CONTROLNETFILEHEADERV0002']._serialized_end=217
# @@protoc_insertion_point(module_scope)
