name: Pull-Request-CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       os: [ubuntu-latest, macos-latest]
       python-version: ["3.9", "3.10", "3.11", "3.12"]   
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup ENV
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          use-mamba: true
          channels: conda-forge, defaults
          channel-priority: strict
          activate-environment: plio
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
      - name: Check build environment
        run: |
          conda list
      - name: Install Python Package
        run: |
          python setup.py install
      - name: Test Python Package
        run: |
           pytest plio --cov-report=xml
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'

  Build-Docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          submodules: true
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@3b0f2504dd76ef23b6d31f291f4913fb60ab5ff3
        with:
          miniconda-version: "latest"
          activate-environment: plio
          environment-file: environment_docs.yml
          auto-activate-base: false
          auto-update-conda: true
      - name: Check doc build environment
        run: |
          conda list
      - name: Build Docs
        run: |
          cd docs
          sphinx-build -b html . public
